---
- name: Configure system dynamic library path
  copy:
    content: "{{ opensrf_install_prefix }}/lib"
    dest: /etc/ld.so.conf.d/opensrf.conf
  notify: ldconfig

- name: Enable SMP in ejabberd
  lineinfile:
    state: present
    backrefs: yes
    dest: /etc/default/ejabberd
    regexp: '^#SMP=.*'
    line: 'SMP=auto'
  notify: Restart ejabberd

- name: Configure ejabberd
  template:
    src: ejabberd.yml.j2
    dest: /etc/ejabberd/ejabberd.yml
    owner: ejabberd
    group: ejabberd
    mode: 0600
  register: ejabber_config
  notify: Restart ejabberd

- name: Force ejabberd restart when config has changed
  meta: flush_handlers

- name: Create ejabberd private users
  ejabberd_user:
    state: present
    username: "{{ item.key }}"
    host: "private.{{ inventory_hostname }}"
    password: "{{ item.value.password }}"
  with_dict: "{{ opensrf_ejabberd_private_users }}"
  no_log: true

- name: Create ejabberd public users
  ejabberd_user:
    state: present
    username: "{{ item.key }}"
    host: "public.{{ inventory_hostname }}"
    password: "{{ item.value.password }}"
  with_dict: "{{ opensrf_ejabberd_public_users }}"
  no_log: true

- name: Copy over opensrf configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ opensrf_install_prefix }}/conf/{{ item }}"
    owner: opensrf
    group: opensrf
    mode: 0644
  with_items:
    - opensrf.xml
    - opensrf_core.xml
  when: no_evergreen|bool

- name: Configure srfsh for opensrf user
  template:
    src: srfsh.xml.j2
    dest: /home/opensrf/.srfsh.xml
  when: no_evergreen|bool

- name: Make sure permissions are right
  file:
    state: directory
    recurse: yes
    owner: opensrf
    group: opensrf
    path: "{{ opensrf_install_prefix }}"
