---
- name: ldconfig
  command: ldconfig
  become: true

- name: Restart ejabberd
  service:
    state: restarted
    name: ejabberd
  notify: Wait for ejabberd

- name: Wait for ejabberd
  wait_for:
    timeout: 7
  delegate_to: localhost
  become: false